### ISSUE TITLE
Cannot perform operation for Unspecified type.

### ISSUE THREAD

**Issue by zhuker** [JamalMulla/ComposePrefs3#13]
I added `SettingsScreen.kt` from the repo to my project and launched it as a preview 
I get this error

```
 java.lang.IllegalArgumentException: Cannot perform operation for Unspecified type.
           at androidx.compose.ui.unit.TextUnitKt.checkArithmetic--R2X_6o(TextUnit.kt:344)
           at com.jamal.composeprefs3.ui.GroupHeaderKt.GroupHeader-iJQMabo(GroupHeader.kt:74)
````

**Comment by nathanfallet** [comment]
Got the same issue; it fails on this line in the GroupHeader:
```kt
fontSize = LocalTextStyle.current.fontSize.times(FontSizeMultiplier)
```
It looks like `LocalTextStyle.current.fontSize` has a problem because in `checkArithmetic`, `isUnspecified` is `true`?
